import numpy as np
import pandas as pd
def read_output(outputfile):
    """
    Reads the output from the full results file generated by panair.
    :param outputfile: Location of the output folder
    :return: pandas dataframe of the output of interest (AoA, cl, cdi)
    """
    column_idx = 13
    first_result_idx = 17

    with open(outputfile, 'r') as f:
        lines = f.readlines()

    columns = lines[column_idx]
    first_result = lines[first_result_idx]
    results = first_result.split()

    result_idx = first_result_idx

    results_tab = []
    while len(results) == 9:
        results_tab.append([results[1], results[3], results[4]])
        result_idx += 3
        results_line = lines[result_idx]
        results = results_line.split()

    results_arr = np.array(results_tab)
    results_df = pd.DataFrame(results_arr, columns=['alpha', 'cl', 'cdi'])
    return results_df

if __name__ == '__main__':
    read_panair_output(r"C:\Users\Daan\Documents\GitHub\SAStest\Panair\ffmf")